import type { Options } from "./validation";

export function generateWebManifest(options: Options): string {
  const bgColor =
    options.background !== "transparent" ? options.background : "#000000";

  return JSON.stringify(
    {
      name: options.appName,
      short_name: options.shortName,
      start_url: "/",
      display: "standalone",
      background_color: bgColor,
      icons: [
        {
          src: "/android-chrome-192x192.png",
          sizes: "192x192",
          type: "image/png",
        },
        {
          src: "/android-chrome-512x512.png",
          sizes: "512x512",
          type: "image/png",
        },
      ],
    },
    null,
    2
  );
}

export function generateHeadSnippet(): string {
  return `<link rel="icon" href="/favicon.ico" sizes="any" />
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
<link rel="manifest" href="/site.webmanifest" />
`;
}

export function generateManifestTs(options: Options): string {
  const bgColor =
    options.background !== "transparent" ? options.background : "#000000";

  return `import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: ${JSON.stringify(options.appName)},
    short_name: ${JSON.stringify(options.shortName)},
    start_url: "/",
    display: "standalone",
    background_color: ${JSON.stringify(bgColor)},
    icons: [
      {
        src: "/android-chrome-192x192.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        src: "/android-chrome-512x512.png",
        sizes: "512x512",
        type: "image/png",
      },
    ],
  };
}
`;
}

export function generateReadme(preset: Options["preset"]): string {
  if (preset === "nextjs-app-router") {
    return `# FaviconKit Output — Next.js App Router

## What's Included

- \`app/favicon.ico\` — Browser tab icon (16/32/48px)
- \`app/icon.png\` — 32x32 PNG icon (used by Next.js metadata)
- \`app/apple-icon.png\` — 180x180 Apple Touch Icon
- \`app/manifest.ts\` — Web App Manifest (TypeScript, MetadataRoute.Manifest)
- \`public/android-chrome-192x192.png\` — Android Chrome icon (192px)
- \`public/android-chrome-512x512.png\` — Android Chrome icon (512px)

## How to Use

1. Copy the \`app/\` files into your project's \`app/\` directory.
2. Copy the \`public/\` files into your project's \`public/\` directory.
3. Next.js App Router automatically picks up \`favicon.ico\`, \`icon.png\`, \`apple-icon.png\`, and \`manifest.ts\` from the \`app/\` directory.

No \`<head>\` snippet needed — Next.js handles it automatically.

---
Generated by FaviconKit
`;
  }

  return `# FaviconKit Output — Classic Web

## What's Included

- \`public/favicon.ico\` — Browser tab icon (16/32/48px)
- \`public/favicon-16x16.png\` — 16x16 PNG icon
- \`public/favicon-32x32.png\` — 32x32 PNG icon
- \`public/favicon-48x48.png\` — 48x48 PNG icon
- \`public/apple-touch-icon.png\` — 180x180 Apple Touch Icon
- \`public/android-chrome-192x192.png\` — Android Chrome icon (192px)
- \`public/android-chrome-512x512.png\` — Android Chrome icon (512px)
- \`public/site.webmanifest\` — Web App Manifest
- \`head-snippet.html\` — HTML \`<head>\` tags to paste into your HTML

## How to Use

1. Copy everything inside \`public/\` into your project's public/static root.
2. Open \`head-snippet.html\` and paste its contents into the \`<head>\` of your HTML.

---
Generated by FaviconKit
`;
}
